### ISSUE TITLE
请问怎么获取我选择的text内容

### ISSUE THREAD

**Issue by Leonzzq** [MajorLMJ/LMJDropdownMenu#1]
请问怎么获取我选择的text内容

**Comment by JerryLMJ** [comment]
在- (void)dropdownMenu:(LMJDropdownMenu *)menu didSelectOptionAtIndex:(NSUInteger)index;代理中获取当前点击的index，然后用这个index在你的数据源里拿

**Comment by Leonzzq** [comment]
好的，谢谢

**Comment by JerryLMJ** [comment]
下个版本在代理中加上这个参数

**Comment by JerryLMJ** [comment]
已升级到2.0.1，代理方法已修改为：- (void)dropdownMenu:(LMJDropdownMenu *)menu didSelectOptionAtIndex:(NSUInteger)index optionTitle:(NSString *)title; ，可通过title获取选项内容。
升级新版本注意修改代理方法！
