### ISSUE TITLE
当设置宽度为全屏时下拉菜单分割线右边会有一部分空白

### ISSUE THREAD

**Issue by dengsss** [MajorLMJ/LMJDropdownMenu#12]
更改下面一处代码即可解决：
UIView * line = [[UIView alloc] initWithFrame:CGRectMake(0, 0, cell.frame.size.width, 0.5)];

将 宽度设置为 self.frame.size.width 问题解决

**Comment by JerryLMJ** [comment]
感谢你的反馈，3.0.3版本已修复
（最近有点忙，修复的有些迟，抱歉）

**Comment by dengsss** [comment]
> 感谢你的反馈，3.0.3版本已修复
> （最近有点忙，修复的有些迟，抱歉）

没事儿，写的挺好的，继续加油。向所有的开源作者致敬！
