### ISSUE TITLE
如何隐藏下拉框？

### ISSUE THREAD

**Issue by YulinLiu1998** [MajorLMJ/LMJDropdownMenu#16]
<img width="594" alt="WeChatae1" src="https://user-images.githubusercontent.com/75724297/119622985-4f22e680-be3a-11eb-8ce4-c21828d4e6c2.png">
我在主页面时，可以正常使用。
<img width="612" alt="WeChat2" src="https://user-images.githubusercontent.com/75724297/119623126-74aff000-be3a-11eb-924c-728b76ace1be.png">
但是，在导出报表页面，我希望下拉菜单能够隐藏。
我进行了设置NavMenu?.hideDropDown()  。  但并不成功。
请问 如何使下拉菜单隐藏？

**Comment by JerryLMJ** [comment]
问题解决了么？
如果用的是最新版本，理论上不存在这个问题，下拉列表弹出之后是无法操作屏幕上的其他区域的（无法进到二级页），点击其他区域会收起下拉列表。
可以详细说下你的操作流程

**Comment by JerryLMJ** [comment]
更新了一下演示demo，看看是不是跟你的应用场景是一样的。

问题先关闭了，如果依然有问题可以重新打开此问题。
