### ISSUE TITLE
我要在一个uiview里面实现三个下拉框，但是我在viewController里面分别写三个下拉框的代理时会报错，请问我应该怎么实现呢？楼主你之前那个两个下拉框的demo还有吗

### ISSUE THREAD

**Issue by Leonzzq** [MajorLMJ/LMJDropdownMenu#3]
我要在一个uiview里面实现三个下拉框，但是我在viewController里面分别写三个下拉框的代理时会报错，请问我应该怎么实现呢？楼主你之前那个两个下拉框的demo还有吗

**Comment by JerryLMJ** [comment]
不太明白‘分别写三个下拉框的代理’的意思，使用多个下拉菜单，实现一套代理方法就可以了，在代理方法中通过menu参数判断代理请求是来自哪个下拉菜单。
demo已更新至2.0.2，我在新的demo中演示了同一个页面中使用两个下拉菜单的写法。
