### ISSUE TITLE
IOS 13系统无法弹出 下拉选

### ISSUE THREAD

**Issue by lbw12345678** [MajorLMJ/LMJDropdownMenu#5]

**Comment by JerryLMJ** [comment]
<img width="394" alt="屏幕快照 2019-11-05 上午11 34 36" src="https://user-images.githubusercontent.com/15794032/68176770-13f36500-ffc1-11e9-8409-d6af90e8f92b.png">

**Comment by JerryLMJ** [comment]
我在模拟器上试了一下是可以的，是不是因为下拉菜单的父视图的空间不够导致下拉列表不显示呢？
可以把你的情况详细的说一下，或者截个图
