### ISSUE TITLE
可以在cell上使用么

### ISSUE THREAD

**Issue by Hynsen** [MajorLMJ/LMJDropdownMenu#7]

**Comment by JerryLMJ** [comment]
理论上是可以的，但是不建议你用在cell上，如果你开启了cell的复用机制可能使用起来会更复杂。而且控件有一个重要的使用条件就是父视图要有足够的空间显示下拉列表，如果你的cell有足够的空间是没问题的。

**Comment by Hynsen** [comment]
是的，谢谢回复
