### ISSUE TITLE
怎么实现点击外部消失的功能？在iphone 11上显示不完全

### ISSUE THREAD

**Issue by lilipu1** [MajorLMJ/LMJDropdownMenu#8]
![下拉列表](https://user-images.githubusercontent.com/20965284/81767139-418a0f80-950a-11ea-93bc-78aeeab98511.jpg)

**Comment by JerryLMJ** [comment]
由于下拉列表是和点击按钮处于同一父视图上，所以不支持点击其他区域消失，并且在navbar上要有足够的空间显示下拉列表

**Comment by xubillde** [comment]
这种应该兼容超过父视图的情况吧？很难保证父视图一定包含这个菜单UI？

**Comment by LiuJinfan** [comment]
把下拉列表加在keywindow上就行了

**Comment by JerryLMJ** [comment]
3.0.0版本已经支持点击区域外隐藏功能，并且不需要考虑父视图是否有足够的空间显示下拉列表的情况。
